# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/andrius/.local/bin/UnrealEngine5
GAMEPROJECTFILE =/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	TopDown2-Linux-DebugGame  \
	TopDown2-Linux-Shipping  \
	TopDown2 \
	TopDown2Editor-Linux-DebugGame  \
	TopDown2Editor-Linux-Shipping  \
	TopDown2Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TopDown2Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TopDown2Editor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

TopDown2-Linux-DebugGame:
	 $(PROJECTBUILD) TopDown2 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDown2-Linux-Shipping:
	 $(PROJECTBUILD) TopDown2 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDown2:
	 $(PROJECTBUILD) TopDown2 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDown2Editor-Linux-DebugGame:
	 $(PROJECTBUILD) TopDown2Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDown2Editor-Linux-Shipping:
	 $(PROJECTBUILD) TopDown2Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDown2Editor:
	 $(PROJECTBUILD) TopDown2Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
