# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/andrius/.local/bin/UnrealEngine5

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	TopDown2-Android-DebugGame  \
	TopDown2-Android-Development  \
	TopDown2-Android-Shipping  \
	TopDown2-Linux-DebugGame  \
	TopDown2-Linux-Development  \
	TopDown2-Linux-Shipping  \
	TopDown2-LinuxArm64-DebugGame  \
	TopDown2-LinuxArm64-Development  \
	TopDown2-LinuxArm64-Shipping  \
	TopDown2 \
	TopDown2Editor-Linux-DebugGame  \
	TopDown2Editor-Linux-Development  \
	TopDown2Editor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TopDown2Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TopDown2Editor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

TopDown2-Android-DebugGame:
	 $(BUILD) TopDown2 Android DebugGame  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-Android-Development:
	 $(BUILD) TopDown2 Android Development  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-Android-Shipping:
	 $(BUILD) TopDown2 Android Shipping  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-Linux-DebugGame:
	 $(BUILD) TopDown2 Linux DebugGame  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-Linux-Development:
	 $(BUILD) TopDown2 Linux Development  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-Linux-Shipping:
	 $(BUILD) TopDown2 Linux Shipping  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-LinuxArm64-DebugGame:
	 $(BUILD) TopDown2 LinuxArm64 DebugGame  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-LinuxArm64-Development:
	 $(BUILD) TopDown2 LinuxArm64 Development  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2-LinuxArm64-Shipping:
	 $(BUILD) TopDown2 LinuxArm64 Shipping  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2: TopDown2-Linux-Development

TopDown2Editor-Linux-DebugGame:
	 $(BUILD) TopDown2Editor Linux DebugGame  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2Editor-Linux-Development:
	 $(BUILD) TopDown2Editor Linux Development  -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" $(ARGS)

TopDown2Editor: TopDown2Editor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/andrius/Projektai/Games/TopDown2/TopDown2.uproject" -Game 

.PHONY: $(TARGETS)
